language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
services:
  - postgresql
install:
  - pip install --upgrade pip  # so we're able to use the latest resolver
  - pip install --use-feature=2020-resolver .
  - pip install pytest
before_script:
  - psql -c "CREATE USER tbtest WITH UNENCRYPTED PASSWORD 'tbtest';" -U postgres
  - psql -c "CREATE DATABASE tbtest WITH OWNER = tbtest;" -U postgres
script:
  - pytest
