language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
services:
  - postgresql
install:
  - pip install pip-tools
  - pip-sync
  - pip install pytest
  - pip install .
before_script:
  - psql -c "CREATE USER tbtest WITH UNENCRYPTED PASSWORD 'tbtest';" -U postgres
  - psql -c "CREATE DATABASE tbtest WITH OWNER = tbtest;" -U postgres
script:
  - pytest
