language: python
python:
  - "3.6"
  - "3.7-dev"
services:
  - postgresql
install:
  - make install
before_script:
  - psql -c "CREATE USER tbtest WITH UNENCRYPTED PASSWORD 'tbtest';" -U postgres
  - psql -c "CREATE DATABASE tbtest WITH OWNER = tbtest;" -U postgres
script:
  - pytest
